server:
  port: 8787
spring:
  application:
    name: employee-service
  h2:
   console:
     enabled: true
     path: /h2-console
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE